apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    app: prometheus
data:
  prometheus.yml: |-
    scrape_configs:
    - job_name: "prometheus"
      static_configs:
        - targets: ["localhost:9090"]

    - job_name: "Spring boot publisher app"
      scrape_interval: 5s
      metrics_path: '/actuator/prometheus'

      static_configs:
        - targets: ["spring-app-service:8080"]

